service: serverless-demo-api

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app
  pythonRequirements:
    zip: true
    slim: true

provider:
  name: aws
  runtime: python3.9

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
